### ISSUE TITLE
Nice SDK! 🔥

### ISSUE THREAD

**Issue by Sammyjo20** [DeschutesDesignGroupLLC/perscom-php-sdk#5]
Hey! 

I like to occasionally look and find SDKs built with Saloon and see how people build them - I was looking through this one and thought it looked really good! Would you like me to add it Saloon's showcase section in the documentation?  

Awesome work ☺️

**Comment by JonErickson** [comment]
Absolutely! Thanks.

**Comment by Sammyjo20** [comment]
Done! https://docs.saloon.dev/conclusion/showcase
