### ISSUE TITLE
[Bug] AbstractBatchCreateRequest does not work with arrays

### ISSUE THREAD

**Issue by jannes-io** [DeschutesDesignGroupLLC/perscom-php-sdk#88]
The `__construct()` method accepts `ResourceObject|array`, but on line 41 of `AbstractBatchCreateRequest`, the `->map(...)`, has a type hint for `ResourceObject`.

To reproduce:
Call a batch endpoint with array as data.

Result:
Perscom\Http\Requests\AbstractBatchCreateRequest::Perscom\Http\Requests\{closure}(): Argument #1 ($resourceObject) must be of type Perscom\Data\ResourceObject, array given

Expected result:
Resources are created

**Comment by jonerickson** [comment]
Hi @jannes-io, the array of `data` should be an array of `ResourceObject`. Are you expecting a different result?

Example 1: Creating only one object.

```
$connection
  ->combatRecords()
  ->batchCreate(
    new ResourceObject(
      data: [
        "user_id" => "1",
        "text" => "This is a test."
      ]
    )
  )
  ->json();
  ```

Example 2: Creating many records:

```
$connection
  ->combatRecords()
  ->batchCreate([
    new ResourceObject(
      data: [
        "user_id" => "1",
        "text" => "This is a test."
      ]
    ),
    new ResourceObject(
      data: [
        "user_id" => "2",
        "text" => "This is a test."
      ]
    )
  ])
  ->json();
  ```

**Comment by jannes-io** [comment]
Yep you’re right, must’ve been a misunderstanding since the other endpoints just accept arrays as data and I thought I could just wrap that in an array for batch create/update 🤦‍♂️

**Comment by jonerickson** [comment]
Gotcha. Yeah since the body of the request is a lot more specific when doing batch requests, similar to search requests, we utilize the 'ResourceObject' to abstract the complexity away versus doing a generic 'POST' create request that just expects a basic key/value pair.
