### ISSUE TITLE
[Feature] Add more resource interfaces for better IDE support

### ISSUE THREAD

**Issue by jannes-io** [DeschutesDesignGroupLLC/perscom-php-sdk#89]
It'd be nice to have interfaces on resources that have certain endpoints so we can use annotations to improve IDE suggestions.

Real world example:
```php
        $recordResource = match ($type) {
            'service' => $perscom->serviceRecords(),
            'award' => $perscom->awardRecords(),
            'combat' => $perscom->combatRecords(),
            'rank' => $perscom->rankRecords(),
            'assignment' => $perscom->assignmentRecords(),
            'qualification' => $perscom->qualificationRecords()
        };
```

All of these resources have the `batchCreate`, `batchUpdate` and `batchDelete` endpoints. So it'd be nice if we could annotate this variable as a "BatchableResource" or use `instanceof` checks so we don't call non-existing methods (name TBD haha).

Currently we only have `ResourceContract`, but that only covers the basic endpoints. It would be nice to have some more interfaces for those that have search, batch, attachments, statuses,..

**Comment by jonerickson** [comment]
Great suggestion!``
